### PR TITLE
[F] Fix progress bar issues with patched stdout

### LINKED ISSUE #74: Bug: Progress bar width not showing correctly in Minecraft
Since Minecraft overrides stdout with its own logger, the progress bar doesn't print correctly at the width. Maybe try printing to the original stdout with `PrintStream ps = new PrintStream(new FileOutputStream(FileDescriptor.out))`

image

### PR DESCRIPTION
**Pull request by hykilpikonna**
Fixes #74

### CODE REVIEW

File: src/main/java/org/hydev/mcpm/utils/ConsoleUtils.java [hunk 1]
```diff
@@ -10,6 +12,7 @@
  */
 public class ConsoleUtils
 {
+    public static final PrintStream RAW_OUT = new PrintStream(new FileOutputStream(FileDescriptor.out));
```
Comment (MstrPikachu) [inline src/main/java/org/hydev/mcpm/utils/ConsoleUtils.java:15]: why this when you could say System.out

Comment (hykilpikonna) [reply src/main/java/org/hydev/mcpm/utils/ConsoleUtils.java:15]: because `System.out` is patched in Minecraft. it redirects to Minecraft's logger which adds a timestamp instead of the actual System.out that just prints raw text

Comment (hykilpikonna) [reply src/main/java/org/hydev/mcpm/utils/ConsoleUtils.java:15]: Or actually we can use system.err and avoid this problem

Comment (hykilpikonna) [reply src/main/java/org/hydev/mcpm/utils/ConsoleUtils.java:15]: But there might be a chance that System.err is patched as well so... I guess this is the safest way

Comment (MstrPikachu) [reply src/main/java/org/hydev/mcpm/utils/ConsoleUtils.java:15]: I thought System.out used FileDescriptor.out by default but ig making it explicit doesn't hurt

**Review by MstrPikachu — APPROVED** [review]
